language: php

php:
  - 8.1
  - 8.2

before_script:
  - travis_retry composer update

script:
  - ./vendor/bin/phpunit

jobs:

  include:
    - stage: Code Quality
      script:
        - ./vendor/bin/phpcs
